// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// dshot_bidir //
// ----------- //

#define dshot_bidir_wrap_target 0
#define dshot_bidir_wrap 3
#define dshot_bidir_pio_version 0

static const uint16_t dshot_bidir_program_instructions[] = {
            //     .wrap_target
    0x7121, //  0: out    x, 1            side 1 [1]
    0x0223, //  1: jmp    !x, 3           side 0 [2]
    0x0200, //  2: jmp    0               side 0 [2]
    0xb242, //  3: nop                    side 1 [2]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dshot_bidir_program = {
    .instructions = dshot_bidir_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = dshot_bidir_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dshot_bidir_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dshot_bidir_wrap_target, offset + dshot_bidir_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

