// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// dshot_bidir_rx //
// -------------- //

#define dshot_bidir_rx_wrap_target 0
#define dshot_bidir_rx_wrap 0
#define dshot_bidir_rx_pio_version 0

static const uint16_t dshot_bidir_rx_program_instructions[] = {
            //     .wrap_target
    0x4001, //  0: in     pins, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dshot_bidir_rx_program = {
    .instructions = dshot_bidir_rx_program_instructions,
    .length = 1,
    .origin = -1,
    .pio_version = dshot_bidir_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dshot_bidir_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dshot_bidir_rx_wrap_target, offset + dshot_bidir_rx_wrap);
    return c;
}
#endif

