// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// sbus_rx_inverted //
// ---------------- //

#define sbus_rx_inverted_wrap_target 0
#define sbus_rx_inverted_wrap 4
#define sbus_rx_inverted_pio_version 0

static const uint16_t sbus_rx_inverted_program_instructions[] = {
            //     .wrap_target
    0x20a0, //  0: wait   1 pin, 0
    0xea28, //  1: set    x, 8                   [10]
    0x4001, //  2: in     pins, 1
    0x0642, //  3: jmp    x--, 2                 [6]
    0x8000, //  4: push   noblock
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sbus_rx_inverted_program = {
    .instructions = sbus_rx_inverted_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = sbus_rx_inverted_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config sbus_rx_inverted_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sbus_rx_inverted_wrap_target, offset + sbus_rx_inverted_wrap);
    return c;
}
#endif

